### ISSUE TITLE
「ここに検索結果が表示されます」が消えない

### ISSUE THREAD

**Issue by teruteru128** [TinyKitten/Timeline#44]
![image](https://user-images.githubusercontent.com/8587246/33802802-61f7973e-ddc3-11e7-8ba4-61667d99096f.png)
[![https://gyazo.com/cba7e3732fd14cf40829ec0de7434de0](https://i.gyazo.com/cba7e3732fd14cf40829ec0de7434de0.png)](https://gyazo.com/cba7e3732fd14cf40829ec0de7434de0)

フォーカスが移動したときに「ここに検索結果が表示されます」（名前がわからない）が消えません。

**Comment by TinyKitten** [comment]
報告感謝します。修正完了です。
